### ISSUE TITLE
Desktop app needs to be able to take a private key and generate links

### ISSUE THREAD

**Issue by James-Sangalli** [alpha-wallet/alpha-wallet-android#292]
So it can create magic links using the key, use Web3j which can be found inside here: https://github.com/James-Sangalli/PaymentServer

**Comment by lyhistory** [comment]
@colourful-land noted, thanks

**Comment by colourful-land** [comment]
HI. your fork https://github.com/lyhistory/alpha-wallet-android doesn't seem to be as updated as the  "desktop-magic-links" branch. Kindly show me your latest work on your fork and I'll pass it to people who are curious of your work here in Taiwan.

**Comment by colourful-land** [comment]
@lyhistory also rename your repo to 'peter's tool' and later we will use that page's RELEASE page to get people to download the installer.

**Comment by lyhistory** [comment]
@colourful-land renamed https://github.com/lyhistory/peter-s-tool ,and the branch is **feature/desktop-magiclink**
still have issues to draw the UI, now the UI is a little bit complicated and because of manually creating it, the UI sometimes doesn't render as expected result, especially the lower portion of the UI, 
after click 'create magic link' button, you have to drag the frame to find it,
and for the Generalized and expired time, I will replace it with date time picker, still have some trouble
![latest](https://user-images.githubusercontent.com/1522513/44001536-9824bac6-9e66-11e8-8d63-29d08af6dc51.png)

**Comment by lyhistory** [comment]
yesterday updated Expire Time using datetimepicker+timezone combobox

**Comment by James-Sangalli** [comment]
@lyhistory he meant the directory not the repository haha

**Comment by lyhistory** [comment]
![latest](https://user-images.githubusercontent.com/1522513/44108021-b5728858-a02b-11e8-9037-f3c09a489dd3.png)

please have a review to confirm whether this version meet the functional requirement, I know there are a lot work to do to improve the look and feel, for example:
1)reset the ticket list to empty
2)too painful to scroll down 100 dropdownlist to find the desired location, need to customize the combobox to add a search filter.
3) the datetime picker is too basic, not ease to use
4) for rendering datepicker ui component based on the XML, I have to hardcode to use the id 'time' to decide whether to render it as a Jtextfied or a datetimepicker, this will cause issue when the xml variant with differenet id or multiple datetime attributes
etc

**Comment by farrahfazirah** [comment]
![tokenid generator](https://user-images.githubusercontent.com/20555752/44139671-591e5580-a0aa-11e8-80d5-ed63123b93b0.png)

1. I have added in a "RESET" button as a suggestion beside the ticket list field
2. I have a question regarding this:
- Is each individual Token ID a dropdown? I'm thinking that you could do something like this https://codepen.io/kaleem78/pen/YjLqXQ where all the Token IDs are in one dropdown field and you could input text on the dropdown field to search for a particular Token ID.
- However, in my UI, in case you still want to add in a search field, I have added in a UI suggestion.
3. I did not add this in the UI above: Can we have a DATE and TIME attribute? There is only TIME attribute. I believe we should add in a DATE attribute to make the date time picker easy to use.

**Comment by lyhistory** [comment]
@farrahfazirah hi, thanks, I added you to the collaborator, the latest is in branch feature/desktop-magiclink 
looks like your code is not synced the latest changes,
and yes I'll keep working on the repo, I listed the above points because I'm so bad at UI design and try to find all the possible improvements from the users perspective

**Comment by colourful-land** [comment]
I close this one so that @farrahfazirah can start a new thread of discussion on peter's repository.
